#ifndef ERROR_MESSAGE_H
# define ERROR_MESSAGE_H

# define SYNTAX_ERR_PIPE 1
# define SYNTAX_ERR_REDIRECT_IN 2
# define SYNTAX_ERR_REDIRECT_OUT 3
# define SYNTAX_ERR_D_REDIRECT_OUT 4
# define SYNTAX_ERR_NEWLINE 5
# define SYNTAX_ERR_HEREDOC 6
# define UNCLOSED_QUOTES_ERR 7

#endif
